# Page settings
baseurl = "localhost:1313"
title = "MSc Econometrics"
languageCode = "en-us"
theme = "hugo-elate-theme"
publishDir = "docs"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = '<img src="https://upload.wikimedia.org/wikipedia/commons/6/6a/UA-Ruhr_Logo.png" height="55">'
    home = "Home"
    work = "The Program"
    testimonials = "Testimonials"
    services = "Application"
    about = "Coordinators"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "<it>Econometrics<it>"
    subtitle = 'A Joint MSc Program of the UA Ruhr Universities <br><br> TU Dortmund University <br> Ruhr University Bochum <br> University of Duisburg-Essen'
    
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Courses"
    description = "Get an overview over the program structure and the curriculum."
    url = "/blog/overview/"
    button = "Course Overview"
    icon = "icon-compass"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "News & Dates"
    description = "Latest news about the program, important dates and events."
    url = "/blog/"
    button = "News"
    icon = "icon-calendar"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Documents"
    description = "Information material such as conditions of study and examination regulations."
    url = "/blog/documents/"
    button = "Links"
    icon = "icon-notebook"
    img = "img_10.jpg"


  # Work section
  [params.work]
    enable = true
    title = "About the Program"
    description = "<span>Econometrics is a four-semester, English-language master's program of the UAR Universities TU Dortmund, Ruhr-University Bochum and the University of Duisburg-Essen. The program is carried out jointly by the faculties of economics of the three universities and the Faculty of Statistics @ TU Dortmund. It combines the expertise and breadth of the participating faculties in empirical economic research and economics with the methodically oriented training of the statisticians and econometricians at Germany's unique Faculty of Statistics. This bundling of training and research skills enables a specialized curriculum for quantitatively-oriented students which covers a wide range of topics in econometrics and applied economics.<br>Students acquire the ability to combine their statistical methodological competence with their proficiency in economics and apply both in an interdisciplinary manner. They gain extensive knowledge of econometric methods and models and an in-depth understanding of central economic causal relationships and resulting econometric questions. The program particularly supports research-interested students in developing theoretical-analytical skills with regard to specific research questions in economics and thus prepares optimally for a doctorate in econometrics or neighbouring disciplines. Graduates are well prepared for a career in econometrics, empirical economics research, evidence-based policy counselling, or operational research.</span>"
    footertext = ''

    [[params.work.row]]
      img = "UARuhrimage.jpg"
      alt = "Image2"
      title = ""
      subtitle = ""
      
    [[params.work.row]]
      img = "caffelatte.jpg"
      alt = "Image2"
      title = ""
      subtitle = ""

# Services section
  [params.services]
    enable = true
    title = "Requirements & Application Process"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Qualifying Degrees"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-graduation"

    [[params.services.item]]
      title = "Academic CV"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Englisch-Language Certificate"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-badge"

  # About section
  [params.about]
    enable = true
    title = "Coordinators"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Carsten Jentsch"
      position = "TU Dortmund University"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "Jentsch.png"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Christoph Hanck"
      position = "University of Duisburg-Essen"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "hanck.png"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: https://coreui.io/v1/demo/pro/AngularJS_Demo/#!/icons/simple-line-icons
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '<br><div><img src="images/mercur.png" height="100" hspace="20"><img src="images/statistik_dortmund.png" height="55" hspace = "20"><img src="images/wiwi_dortmund.png" height="60" hspace = "21"><img src="images/wiwi_bochum.png" height="60" hspace = "20"><img src="images/wiwi_essen.png" height="60" hspace = "20"><img src="images/RGS.JPG" height="60"></div>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
